// Generated by rstantools.  Do not edit by hand.

/*
    FlexReg is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    FlexReg is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with FlexReg.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_Beta01_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 104> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 21, column 1 to column 16)",
  " (in 'string', line 22, column 1 to column 19)",
  " (in 'string', line 23, column 1 to column 19)",
  " (in 'string', line 24, column 1 to column 19)",
  " (in 'string', line 27, column 1 to column 32)",
  " (in 'string', line 28, column 1 to column 22)",
  " (in 'string', line 29, column 1 to column 22)",
  " (in 'string', line 30, column 1 to column 26)",
  " (in 'string', line 31, column 1 to column 26)",
  " (in 'string', line 32, column 1 to column 32)",
  " (in 'string', line 33, column 1 to column 32)",
  " (in 'string', line 93, column 1 to column 19)",
  " (in 'string', line 34, column 1 to column 24)",
  " (in 'string', line 35, column 1 to column 24)",
  " (in 'string', line 37, column 1 to column 37)",
  " (in 'string', line 38, column 1 to column 37)",
  " (in 'string', line 36, column 15 to line 39, column 2)",
  " (in 'string', line 36, column 1 to line 39, column 2)",
  " (in 'string', line 47, column 2 to column 27)",
  " (in 'string', line 46, column 6 to line 47, column 27)",
  " (in 'string', line 45, column 2 to column 29)",
  " (in 'string', line 44, column 6 to line 47, column 27)",
  " (in 'string', line 43, column 2 to column 21)",
  " (in 'string', line 42, column 6 to line 47, column 27)",
  " (in 'string', line 41, column 2 to column 27)",
  " (in 'string', line 40, column 1 to line 47, column 27)",
  " (in 'string', line 49, column 1 to column 22)",
  " (in 'string', line 50, column 1 to column 18)",
  " (in 'string', line 48, column 14 to line 51, column 1)",
  " (in 'string', line 48, column 0 to line 51, column 1)",
  " (in 'string', line 105, column 0 to column 60)",
  " (in 'string', line 102, column 0 to column 25)",
  " (in 'string', line 100, column 0 to line 105, column 60)",
  " (in 'string', line 99, column 4 to line 106, column 1)",
  " (in 'string', line 97, column 0 to column 25)",
  " (in 'string', line 95, column 0 to line 106, column 1)",
  " (in 'string', line 94, column 13 to line 107, column 1)",
  " (in 'string', line 94, column 0 to line 107, column 1)",
  " (in 'string', line 58, column 1 to column 30)",
  " (in 'string', line 57, column 6 to line 58, column 30)",
  " (in 'string', line 56, column 1 to column 34)",
  " (in 'string', line 55, column 1 to line 58, column 30)",
  " (in 'string', line 63, column 2 to column 39)",
  " (in 'string', line 62, column 6 to line 63, column 39)",
  " (in 'string', line 61, column 2 to column 39)",
  " (in 'string', line 60, column 1 to line 63, column 39)",
  " (in 'string', line 59, column 16 to line 64, column 2)",
  " (in 'string', line 59, column 1 to line 64, column 2)",
  " (in 'string', line 69, column 2 to column 43)",
  " (in 'string', line 68, column 6 to line 69, column 43)",
  " (in 'string', line 67, column 2 to column 43)",
  " (in 'string', line 66, column 1 to line 69, column 43)",
  " (in 'string', line 65, column 17 to line 70, column 2)",
  " (in 'string', line 65, column 1 to line 70, column 2)",
  " (in 'string', line 75, column 2 to column 43)",
  " (in 'string', line 74, column 6 to line 75, column 43)",
  " (in 'string', line 73, column 2 to column 43)",
  " (in 'string', line 72, column 1 to line 75, column 43)",
  " (in 'string', line 71, column 17 to line 76, column 2)",
  " (in 'string', line 71, column 1 to line 76, column 2)",
  " (in 'string', line 88, column 0 to column 57)",
  " (in 'string', line 85, column 0 to column 21)",
  " (in 'string', line 84, column 0 to line 88, column 57)",
  " (in 'string', line 83, column 4 to line 89, column 1)",
  " (in 'string', line 81, column 0 to column 21)",
  " (in 'string', line 79, column 0 to line 89, column 1)",
  " (in 'string', line 78, column 13 to line 90, column 1)",
  " (in 'string', line 78, column 0 to line 90, column 1)",
  " (in 'string', line 2, column 1 to column 16)",
  " (in 'string', line 3, column 8 to column 9)",
  " (in 'string', line 3, column 1 to column 16)",
  " (in 'string', line 4, column 1 to column 16)",
  " (in 'string', line 5, column 1 to column 17)",
  " (in 'string', line 6, column 1 to column 17)",
  " (in 'string', line 7, column 8 to column 9)",
  " (in 'string', line 7, column 10 to column 11)",
  " (in 'string', line 7, column 1 to column 18)",
  " (in 'string', line 8, column 8 to column 9)",
  " (in 'string', line 8, column 10 to column 12)",
  " (in 'string', line 8, column 1 to column 20)",
  " (in 'string', line 9, column 8 to column 9)",
  " (in 'string', line 9, column 10 to column 12)",
  " (in 'string', line 9, column 1 to column 20)",
  " (in 'string', line 10, column 1 to column 27)",
  " (in 'string', line 11, column 1 to column 30)",
  " (in 'string', line 12, column 1 to column 32)",
  " (in 'string', line 13, column 1 to column 32)",
  " (in 'string', line 14, column 1 to column 22)",
  " (in 'string', line 15, column 1 to column 24)",
  " (in 'string', line 16, column 1 to column 24)",
  " (in 'string', line 17, column 1 to column 29)",
  " (in 'string', line 18, column 1 to column 25)",
  " (in 'string', line 21, column 8 to column 9)",
  " (in 'string', line 22, column 8 to column 10)",
  " (in 'string', line 23, column 8 to column 10)",
  " (in 'string', line 27, column 25 to column 26)",
  " (in 'string', line 28, column 17 to column 18)",
  " (in 'string', line 29, column 17 to column 18)",
  " (in 'string', line 30, column 17 to column 18)",
  " (in 'string', line 31, column 17 to column 18)",
  " (in 'string', line 32, column 26 to column 27)",
  " (in 'string', line 33, column 26 to column 27)",
  " (in 'string', line 93, column 8 to column 9)"};
#include <stan_meta_header.hpp>
class model_Beta01 final : public model_base_crtp<model_Beta01> {
private:
  int N;
  Eigen::Matrix<double,-1,1> y_data__;
  int K;
  int K1;
  int K0;
  Eigen::Matrix<double,-1,-1> X_data__;
  Eigen::Matrix<double,-1,-1> X1_data__;
  Eigen::Matrix<double,-1,-1> X0_data__;
  int link_code_mu;
  int link_prior_beta;
  int link_prior_omega1;
  int link_prior_omega0;
  double hyperprior_beta;
  double hyperprior_omega1;
  double hyperprior_omega0;
  int prior_code_phi;
  double hyper_phi;
  Eigen::Map<Eigen::Matrix<double,-1,1>> y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X1{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X0{nullptr, 0, 0};
public:
  ~model_Beta01() {}
  model_Beta01(stan::io::var_context& context__, unsigned int
               random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_Beta01_namespace::model_Beta01";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 69;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 69;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 69;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 71;
      context__.validate_dims("data initialization", "y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      y_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double,-1,1>>(y_data__.data(), N);
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 71;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 71;
        pos__ = 1;
        current_statement__ = 71;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 71;
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          current_statement__ = 71;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 72;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 72;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 72;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 73;
      context__.validate_dims("data initialization", "K1", "int",
        std::vector<size_t>{});
      K1 = std::numeric_limits<int>::min();
      current_statement__ = 73;
      K1 = context__.vals_i("K1")[(1 - 1)];
      current_statement__ = 73;
      stan::math::check_greater_or_equal(function__, "K1", K1, 1);
      current_statement__ = 74;
      context__.validate_dims("data initialization", "K0", "int",
        std::vector<size_t>{});
      K0 = std::numeric_limits<int>::min();
      current_statement__ = 74;
      K0 = context__.vals_i("K0")[(1 - 1)];
      current_statement__ = 74;
      stan::math::check_greater_or_equal(function__, "K0", K0, 1);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("X", "K", K);
      current_statement__ = 77;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, K);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 77;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 77;
        pos__ = 1;
        current_statement__ = 77;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 77;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 77;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 77;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 78;
      stan::math::validate_non_negative_index("X1", "N", N);
      current_statement__ = 79;
      stan::math::validate_non_negative_index("X1", "K1", K1);
      current_statement__ = 80;
      context__.validate_dims("data initialization", "X1", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K1)});
      X1_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K1,
                    std::numeric_limits<double>::quiet_NaN());
      new (&X1) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X1_data__.data(), N,
        K1);
      {
        std::vector<local_scalar_t__> X1_flat__;
        current_statement__ = 80;
        X1_flat__ = context__.vals_r("X1");
        current_statement__ = 80;
        pos__ = 1;
        current_statement__ = 80;
        for (int sym1__ = 1; sym1__ <= K1; ++sym1__) {
          current_statement__ = 80;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 80;
            stan::model::assign(X1, X1_flat__[(pos__ - 1)],
              "assigning variable X1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 80;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 81;
      stan::math::validate_non_negative_index("X0", "N", N);
      current_statement__ = 82;
      stan::math::validate_non_negative_index("X0", "K0", K0);
      current_statement__ = 83;
      context__.validate_dims("data initialization", "X0", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K0)});
      X0_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K0,
                    std::numeric_limits<double>::quiet_NaN());
      new (&X0) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X0_data__.data(), N,
        K0);
      {
        std::vector<local_scalar_t__> X0_flat__;
        current_statement__ = 83;
        X0_flat__ = context__.vals_r("X0");
        current_statement__ = 83;
        pos__ = 1;
        current_statement__ = 83;
        for (int sym1__ = 1; sym1__ <= K0; ++sym1__) {
          current_statement__ = 83;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 83;
            stan::model::assign(X0, X0_flat__[(pos__ - 1)],
              "assigning variable X0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 83;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 84;
      context__.validate_dims("data initialization", "link_code_mu", "int",
        std::vector<size_t>{});
      link_code_mu = std::numeric_limits<int>::min();
      current_statement__ = 84;
      link_code_mu = context__.vals_i("link_code_mu")[(1 - 1)];
      current_statement__ = 84;
      stan::math::check_greater_or_equal(function__, "link_code_mu",
        link_code_mu, 1);
      current_statement__ = 85;
      context__.validate_dims("data initialization", "link_prior_beta",
        "int", std::vector<size_t>{});
      link_prior_beta = std::numeric_limits<int>::min();
      current_statement__ = 85;
      link_prior_beta = context__.vals_i("link_prior_beta")[(1 - 1)];
      current_statement__ = 85;
      stan::math::check_greater_or_equal(function__, "link_prior_beta",
        link_prior_beta, 1);
      current_statement__ = 86;
      context__.validate_dims("data initialization", "link_prior_omega1",
        "int", std::vector<size_t>{});
      link_prior_omega1 = std::numeric_limits<int>::min();
      current_statement__ = 86;
      link_prior_omega1 = context__.vals_i("link_prior_omega1")[(1 - 1)];
      current_statement__ = 86;
      stan::math::check_greater_or_equal(function__, "link_prior_omega1",
        link_prior_omega1, 1);
      current_statement__ = 87;
      context__.validate_dims("data initialization", "link_prior_omega0",
        "int", std::vector<size_t>{});
      link_prior_omega0 = std::numeric_limits<int>::min();
      current_statement__ = 87;
      link_prior_omega0 = context__.vals_i("link_prior_omega0")[(1 - 1)];
      current_statement__ = 87;
      stan::math::check_greater_or_equal(function__, "link_prior_omega0",
        link_prior_omega0, 1);
      current_statement__ = 88;
      context__.validate_dims("data initialization", "hyperprior_beta",
        "double", std::vector<size_t>{});
      hyperprior_beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 88;
      hyperprior_beta = context__.vals_r("hyperprior_beta")[(1 - 1)];
      current_statement__ = 89;
      context__.validate_dims("data initialization", "hyperprior_omega1",
        "double", std::vector<size_t>{});
      hyperprior_omega1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 89;
      hyperprior_omega1 = context__.vals_r("hyperprior_omega1")[(1 - 1)];
      current_statement__ = 90;
      context__.validate_dims("data initialization", "hyperprior_omega0",
        "double", std::vector<size_t>{});
      hyperprior_omega0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 90;
      hyperprior_omega0 = context__.vals_r("hyperprior_omega0")[(1 - 1)];
      current_statement__ = 91;
      context__.validate_dims("data initialization", "prior_code_phi", "int",
        std::vector<size_t>{});
      prior_code_phi = std::numeric_limits<int>::min();
      current_statement__ = 91;
      prior_code_phi = context__.vals_i("prior_code_phi")[(1 - 1)];
      current_statement__ = 91;
      stan::math::check_greater_or_equal(function__, "prior_code_phi",
        prior_code_phi, 1);
      current_statement__ = 92;
      context__.validate_dims("data initialization", "hyper_phi", "double",
        std::vector<size_t>{});
      hyper_phi = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 92;
      hyper_phi = context__.vals_r("hyper_phi")[(1 - 1)];
      current_statement__ = 92;
      stan::math::check_greater_or_equal(function__, "hyper_phi", hyper_phi,
        0);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("beta", "K", K);
      current_statement__ = 94;
      stan::math::validate_non_negative_index("omega1", "K1", K1);
      current_statement__ = 95;
      stan::math::validate_non_negative_index("omega0", "K0", K0);
      current_statement__ = 96;
      stan::math::validate_non_negative_index("mu", "N", N);
      current_statement__ = 97;
      stan::math::validate_non_negative_index("a", "N", N);
      current_statement__ = 98;
      stan::math::validate_non_negative_index("b", "N", N);
      current_statement__ = 99;
      stan::math::validate_non_negative_index("reg1", "N", N);
      current_statement__ = 100;
      stan::math::validate_non_negative_index("reg0", "N", N);
      current_statement__ = 101;
      stan::math::validate_non_negative_index("q1", "N", N);
      current_statement__ = 102;
      stan::math::validate_non_negative_index("q0", "N", N);
      current_statement__ = 103;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = K + K1 + K0 + 1;
  }
  inline std::string model_name() const final {
    return "model_Beta01";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_Beta01_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<local_scalar_t__,-1,1> omega1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K1, DUMMY_VAR__);
      current_statement__ = 2;
      omega1 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K1);
      Eigen::Matrix<local_scalar_t__,-1,1> omega0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K0, DUMMY_VAR__);
      current_statement__ = 3;
      omega0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K0);
      local_scalar_t__ phi = DUMMY_VAR__;
      current_statement__ = 4;
      phi = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> a =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> b =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> reg1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> reg0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> q1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> q0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 13;
      stan::model::assign(reg1,
        stan::math::exp(stan::math::multiply(X1, omega1)),
        "assigning variable reg1");
      current_statement__ = 14;
      stan::model::assign(reg0,
        stan::math::exp(stan::math::multiply(X0, omega0)),
        "assigning variable reg0");
      current_statement__ = 18;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 15;
        stan::model::assign(q1,
          (stan::model::rvalue(reg1, "reg1", stan::model::index_uni(i)) / ((1
          + stan::model::rvalue(reg1, "reg1", stan::model::index_uni(i))) +
          stan::model::rvalue(reg0, "reg0", stan::model::index_uni(i)))),
          "assigning variable q1", stan::model::index_uni(i));
        current_statement__ = 16;
        stan::model::assign(q0,
          (stan::model::rvalue(reg0, "reg0", stan::model::index_uni(i)) / ((1
          + stan::model::rvalue(reg1, "reg1", stan::model::index_uni(i))) +
          stan::model::rvalue(reg0, "reg0", stan::model::index_uni(i)))),
          "assigning variable q0", stan::model::index_uni(i));
      }
      current_statement__ = 26;
      if (stan::math::logical_eq(link_code_mu, 1)) {
        current_statement__ = 25;
        stan::model::assign(mu,
          stan::math::inv_logit(stan::math::multiply(X, beta)),
          "assigning variable mu");
      } else {
        current_statement__ = 24;
        if (stan::math::logical_eq(link_code_mu, 2)) {
          current_statement__ = 23;
          stan::model::assign(mu,
            stan::math::Phi(stan::math::multiply(X, beta)),
            "assigning variable mu");
        } else {
          current_statement__ = 22;
          if (stan::math::logical_eq(link_code_mu, 3)) {
            current_statement__ = 21;
            stan::model::assign(mu,
              stan::math::inv_cloglog(stan::math::multiply(X, beta)),
              "assigning variable mu");
          } else {
            current_statement__ = 20;
            if (stan::math::logical_eq(link_code_mu, 4)) {
              current_statement__ = 19;
              stan::model::assign(mu,
                stan::math::exp(
                  stan::math::minus(
                    stan::math::exp(stan::math::multiply(X, beta)))),
                "assigning variable mu");
            }
          }
        }
      }
      current_statement__ = 30;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 27;
        stan::model::assign(b, ((1 -
          stan::model::rvalue(mu, "mu", stan::model::index_uni(i))) * phi),
          "assigning variable b", stan::model::index_uni(i));
        current_statement__ = 28;
        stan::model::assign(a,
          (stan::model::rvalue(mu, "mu", stan::model::index_uni(i)) * phi),
          "assigning variable a", stan::model::index_uni(i));
      }
      current_statement__ = 5;
      stan::math::check_greater_or_equal(function__, "mu", mu, 0);
      current_statement__ = 5;
      stan::math::check_less_or_equal(function__, "mu", mu, 1);
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "a", a, 0);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "b", b, 0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "reg1", reg1, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "reg0", reg0, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "q1", q1, 0);
      current_statement__ = 10;
      stan::math::check_less_or_equal(function__, "q1", q1, 1);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "q0", q0, 0);
      current_statement__ = 11;
      stan::math::check_less_or_equal(function__, "q0", q0, 1);
      {
        current_statement__ = 42;
        if (stan::math::logical_eq(prior_code_phi, 1)) {
          current_statement__ = 41;
          lp_accum__.add(stan::math::gamma_lpdf<propto__>(phi, hyper_phi,
                           hyper_phi));
        } else {
          current_statement__ = 40;
          if (stan::math::logical_eq(prior_code_phi, 2)) {
            current_statement__ = 39;
            lp_accum__.add(stan::math::uniform_lpdf<propto__>(phi, 0.0,
                             hyper_phi));
          }
        }
        current_statement__ = 48;
        for (int l = 1; l <= K; ++l) {
          current_statement__ = 46;
          if (stan::math::logical_eq(link_prior_beta, 1)) {
            current_statement__ = 45;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(
                             stan::model::rvalue(beta, "beta",
                               stan::model::index_uni(l)), 0, hyperprior_beta));
          } else {
            current_statement__ = 44;
            if (stan::math::logical_eq(link_prior_beta, 2)) {
              current_statement__ = 43;
              lp_accum__.add(stan::math::cauchy_lpdf<propto__>(
                               stan::model::rvalue(beta, "beta",
                                 stan::model::index_uni(l)), 0,
                               hyperprior_beta));
            }
          }
        }
        current_statement__ = 54;
        for (int l = 1; l <= K1; ++l) {
          current_statement__ = 52;
          if (stan::math::logical_eq(link_prior_omega1, 1)) {
            current_statement__ = 51;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(
                             stan::model::rvalue(omega1, "omega1",
                               stan::model::index_uni(l)), 0,
                             hyperprior_omega1));
          } else {
            current_statement__ = 50;
            if (stan::math::logical_eq(link_prior_omega1, 2)) {
              current_statement__ = 49;
              lp_accum__.add(stan::math::cauchy_lpdf<propto__>(
                               stan::model::rvalue(omega1, "omega1",
                                 stan::model::index_uni(l)), 0,
                               hyperprior_omega1));
            }
          }
        }
        current_statement__ = 60;
        for (int l = 1; l <= K0; ++l) {
          current_statement__ = 58;
          if (stan::math::logical_eq(link_prior_omega0, 1)) {
            current_statement__ = 57;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(
                             stan::model::rvalue(omega0, "omega0",
                               stan::model::index_uni(l)), 0,
                             hyperprior_omega0));
          } else {
            current_statement__ = 56;
            if (stan::math::logical_eq(link_prior_omega0, 2)) {
              current_statement__ = 55;
              lp_accum__.add(stan::math::cauchy_lpdf<propto__>(
                               stan::model::rvalue(omega0, "omega0",
                                 stan::model::index_uni(l)), 0,
                               hyperprior_omega0));
            }
          }
        }
        current_statement__ = 68;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 66;
          if (stan::math::logical_eq(
                stan::model::rvalue(y, "y", stan::model::index_uni(i)), 1)) {
            current_statement__ = 65;
            lp_accum__.add(stan::math::log(
                             stan::model::rvalue(q1, "q1",
                               stan::model::index_uni(i))));
          } else {
            current_statement__ = 63;
            if (stan::math::logical_eq(
                  stan::model::rvalue(y, "y", stan::model::index_uni(i)), 0)) {
              current_statement__ = 62;
              lp_accum__.add(stan::math::log(
                               stan::model::rvalue(q0, "q0",
                                 stan::model::index_uni(i))));
            } else {
              current_statement__ = 61;
              lp_accum__.add((stan::math::log(((1 -
                                stan::model::rvalue(q0, "q0",
                                  stan::model::index_uni(i))) -
                                stan::model::rvalue(q1, "q1",
                                  stan::model::index_uni(i)))) +
                stan::math::beta_lpdf<false>(
                  stan::model::rvalue(y, "y", stan::model::index_uni(i)),
                  stan::model::rvalue(a, "a", stan::model::index_uni(i)),
                  stan::model::rvalue(b, "b", stan::model::index_uni(i)))));
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_Beta01_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<double,-1,1> omega1 =
        Eigen::Matrix<double,-1,1>::Constant(K1,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      omega1 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K1);
      Eigen::Matrix<double,-1,1> omega0 =
        Eigen::Matrix<double,-1,1>::Constant(K0,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      omega0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K0);
      double phi = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      phi = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> a =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> b =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> reg1 =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> reg0 =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> q1 =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> q0 =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(beta);
      out__.write(omega1);
      out__.write(omega0);
      out__.write(phi);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 13;
      stan::model::assign(reg1,
        stan::math::exp(stan::math::multiply(X1, omega1)),
        "assigning variable reg1");
      current_statement__ = 14;
      stan::model::assign(reg0,
        stan::math::exp(stan::math::multiply(X0, omega0)),
        "assigning variable reg0");
      current_statement__ = 18;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 15;
        stan::model::assign(q1,
          (stan::model::rvalue(reg1, "reg1", stan::model::index_uni(i)) / ((1
          + stan::model::rvalue(reg1, "reg1", stan::model::index_uni(i))) +
          stan::model::rvalue(reg0, "reg0", stan::model::index_uni(i)))),
          "assigning variable q1", stan::model::index_uni(i));
        current_statement__ = 16;
        stan::model::assign(q0,
          (stan::model::rvalue(reg0, "reg0", stan::model::index_uni(i)) / ((1
          + stan::model::rvalue(reg1, "reg1", stan::model::index_uni(i))) +
          stan::model::rvalue(reg0, "reg0", stan::model::index_uni(i)))),
          "assigning variable q0", stan::model::index_uni(i));
      }
      current_statement__ = 26;
      if (stan::math::logical_eq(link_code_mu, 1)) {
        current_statement__ = 25;
        stan::model::assign(mu,
          stan::math::inv_logit(stan::math::multiply(X, beta)),
          "assigning variable mu");
      } else {
        current_statement__ = 24;
        if (stan::math::logical_eq(link_code_mu, 2)) {
          current_statement__ = 23;
          stan::model::assign(mu,
            stan::math::Phi(stan::math::multiply(X, beta)),
            "assigning variable mu");
        } else {
          current_statement__ = 22;
          if (stan::math::logical_eq(link_code_mu, 3)) {
            current_statement__ = 21;
            stan::model::assign(mu,
              stan::math::inv_cloglog(stan::math::multiply(X, beta)),
              "assigning variable mu");
          } else {
            current_statement__ = 20;
            if (stan::math::logical_eq(link_code_mu, 4)) {
              current_statement__ = 19;
              stan::model::assign(mu,
                stan::math::exp(
                  stan::math::minus(
                    stan::math::exp(stan::math::multiply(X, beta)))),
                "assigning variable mu");
            }
          }
        }
      }
      current_statement__ = 30;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 27;
        stan::model::assign(b, ((1 -
          stan::model::rvalue(mu, "mu", stan::model::index_uni(i))) * phi),
          "assigning variable b", stan::model::index_uni(i));
        current_statement__ = 28;
        stan::model::assign(a,
          (stan::model::rvalue(mu, "mu", stan::model::index_uni(i)) * phi),
          "assigning variable a", stan::model::index_uni(i));
      }
      current_statement__ = 5;
      stan::math::check_greater_or_equal(function__, "mu", mu, 0);
      current_statement__ = 5;
      stan::math::check_less_or_equal(function__, "mu", mu, 1);
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "a", a, 0);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "b", b, 0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "reg1", reg1, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "reg0", reg0, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "q1", q1, 0);
      current_statement__ = 10;
      stan::math::check_less_or_equal(function__, "q1", q1, 1);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "q0", q0, 0);
      current_statement__ = 11;
      stan::math::check_less_or_equal(function__, "q0", q0, 1);
      if (emit_transformed_parameters__) {
        out__.write(mu);
        out__.write(a);
        out__.write(b);
        out__.write(reg1);
        out__.write(reg0);
        out__.write(q1);
        out__.write(q0);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 38;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 36;
        if (stan::math::logical_eq(
              stan::model::rvalue(y, "y", stan::model::index_uni(i)), 1)) {
          current_statement__ = 35;
          stan::model::assign(log_lik,
            stan::math::log(
              stan::model::rvalue(q1, "q1", stan::model::index_uni(i))),
            "assigning variable log_lik", stan::model::index_uni(i));
        } else {
          current_statement__ = 33;
          if (stan::math::logical_eq(
                stan::model::rvalue(y, "y", stan::model::index_uni(i)), 0)) {
            current_statement__ = 32;
            stan::model::assign(log_lik,
              stan::math::log(
                stan::model::rvalue(q0, "q0", stan::model::index_uni(i))),
              "assigning variable log_lik", stan::model::index_uni(i));
          } else {
            current_statement__ = 31;
            stan::model::assign(log_lik,
              (stan::math::log(((1 -
                 stan::model::rvalue(q0, "q0", stan::model::index_uni(i))) -
                 stan::model::rvalue(q1, "q1", stan::model::index_uni(i)))) +
              stan::math::beta_lpdf<false>(
                stan::model::rvalue(y, "y", stan::model::index_uni(i)),
                stan::model::rvalue(a, "a", stan::model::index_uni(i)),
                stan::model::rvalue(b, "b", stan::model::index_uni(i)))),
              "assigning variable log_lik", stan::model::index_uni(i));
          }
        }
      }
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable beta");
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> omega1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K1, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(omega1,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K1),
        "assigning variable omega1");
      out__.write(omega1);
      Eigen::Matrix<local_scalar_t__,-1,1> omega0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K0, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(omega0,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K0),
        "assigning variable omega0");
      out__.write(omega0);
      local_scalar_t__ phi = DUMMY_VAR__;
      current_statement__ = 4;
      phi = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, phi);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "omega1", "double",
        std::vector<size_t>{static_cast<size_t>(K1)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "omega0", "double",
        std::vector<size_t>{static_cast<size_t>(K0)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "phi", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 1;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> omega1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K1, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> omega1_flat__;
        current_statement__ = 2;
        omega1_flat__ = context__.vals_r("omega1");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K1; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(omega1, omega1_flat__[(pos__ - 1)],
            "assigning variable omega1", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(omega1);
      Eigen::Matrix<local_scalar_t__,-1,1> omega0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K0, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> omega0_flat__;
        current_statement__ = 3;
        omega0_flat__ = context__.vals_r("omega0");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K0; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(omega0, omega0_flat__[(pos__ - 1)],
            "assigning variable omega0", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(omega0);
      local_scalar_t__ phi = DUMMY_VAR__;
      current_statement__ = 4;
      phi = context__.vals_r("phi")[(1 - 1)];
      out__.write_free_lb(0, phi);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta", "omega1", "omega0", "phi"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"mu", "a", "b", "reg1", "reg0", "q1", "q0"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K1)},
                std::vector<size_t>{static_cast<size_t>(K0)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K1; ++sym1__) {
      param_names__.emplace_back(std::string() + "omega1" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K0; ++sym1__) {
      param_names__.emplace_back(std::string() + "omega0" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "phi");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "a" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "b" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "reg1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "reg0" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "q1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "q0" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K1; ++sym1__) {
      param_names__.emplace_back(std::string() + "omega1" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K0; ++sym1__) {
      param_names__.emplace_back(std::string() + "omega0" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "phi");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "a" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "b" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "reg1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "reg0" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "q1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "q0" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"omega1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K1) + "},\"block\":\"parameters\"},{\"name\":\"omega0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K0) + "},\"block\":\"parameters\"},{\"name\":\"phi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"a\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"reg1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"reg0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"q1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"q0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"omega1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K1) + "},\"block\":\"parameters\"},{\"name\":\"omega0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K0) + "},\"block\":\"parameters\"},{\"name\":\"phi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"a\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"reg1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"reg0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"q1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"q0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((K + K1) + K0) + 1);
    const size_t num_transformed = emit_transformed_parameters * (((((((N +
      N) + N) + N) + N) + N) + N));
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((K + K1) + K0) + 1);
    const size_t num_transformed = emit_transformed_parameters * (((((((N +
      N) + N) + N) + N) + N) + N));
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_Beta01_namespace::model_Beta01;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_Beta01_namespace::profiles__;
}
#endif
#endif
